version: '3'

services:

  traefik:
    image: traefik:v2.10
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --accesslog=true
      - --log.level=DEBUG
      - --providers.file=true
      - --providers.file.directory=/traefik/config
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false

      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.websecure.address=:443
    ports:
      - "81:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik:/traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN:-cyclecounter.localhost}`)"
      - "traefik.docker.network=wmcycledata_traefik_web"
    environment:
      DOMAIN: ${DOMAIN:-cyclecounter.localhost}
    networks: 
      - traefik_web

  web:
    build:
      context: ./web
      target: dev
    environment:
      REACT_APP_HOST: ${DOMAIN:-cyclecounter.localhost}
    # labels:
      # - "traefik.http.routers.web.rule=Host(`${DOMAIN:-badlyparked.localhost}`)"
    volumes:
      - "./web/src:/app/src"
      - "./web/public:/app/public"

  
  api:
    build:
      context: ./api
      target: dev
      
    volumes:
      - "./api:/app"

networks:
  traefik_web:
    external:
      false
