version: '3'
services:
  db:
    build: ./postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      API_DB: "api"
      API_DB_USER: "${API_DB_USERNAME}"
      API_DB_PASSWORD: "${API_DB_PASSWORD}"
    volumes:
      - "db_data:/var/lib/postgresql/data" 
    networks:
      - traefik_web

  web:
      build:
        context: ./web
        # target: prod
        args:
          REACT_APP_HOST: ${DOMAIN:-cyclecounter.co.uk}
      restart: unless-stopped
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.bs_web.loadbalancer.server.port=80"
        - "traefik.http.routers.bs_web.tls.certresolver=letsEncrypt"
        - "traefik.http.routers.bs_web.service=bs_web"
        - "traefik.http.routers.bs_web.rule=Host(`${DOMAIN:-cyclecounter.localhost}`)"
        - "traefik.http.routers.bs_web.tls=true"
      networks:
        - traefik_web
  api:

    build:
      context: ./api
      # target: prod
    restart: unless-stopped
    # depends_on:
    #   db:
    #     condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bs_api.tls=true"
      - "traefik.http.routers.bs_api.tls.certresolver=letsEncrypt"
      -  "traefik.http.services.bs_api.loadbalancer.server.port=80"
      - "traefik.http.routers.bs_api.rule=Host(`${DOMAIN:-cyclecounter.localhost}`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.strip_api.stripprefix.prefixes=/api"
      - "traefik.http.routers.bs_api.middlewares=strip_api"
    environment:
      DOMAIN: "${DOMAIN:-cyclecounter.localhost}"
      DATABASE_URL: "postgresql://${API_DB_USERNAME}:${API_DB_PASSWORD}@db/api"
      ADMIN_LIST: "${ADMIN_LIST}"
      SESSION_SECRET: "${SESSION_SECRET}"
      DISCORD_OAUTH_CLIENT_ID: "${DISCORD_OAUTH_CLIENT_ID}"
      DISCORD_OAUTH_CLIENT_SECRET: "${DISCORD_OAUTH_CLIENT_SECRET}"
      TWITTER_OAUTH_CLIENT_ID: "${TWITTER_OAUTH_CLIENT_ID}"
      TWITTER_OAUTH_CLIENT_SECRET: "${TWITTER_OAUTH_CLIENT_SECRET}"
      EXTERNAL_API_TOKEN: "${EXTERNAL_API_TOKEN}"
    networks:
      - traefik_web


networks:
  traefik_web:
    external:
            true

volumes:
  db_data:
