FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9 as prod

ENV FORWARDED_ALLOW_IPS="*"

RUN pip install -U pip

COPY ./ /app/
RUN pip install -r requirements.txt
RUN pip install SQLAlchemy
RUN pip install pydantic
RUN pip install psycopg2
RUN pip install requests

ENV MODULE_NAME=API.main
FROM prod as dev

CMD /start-reload.sh